# Generated by Django 3.0.5 on 2020-04-05 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        ('reports', '0002_declared_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspectedcase',
            name='attachment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='attachments.Attachment'),
        ),
    ]
