# Generated by Django 3.0.5 on 2020-04-05 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
        ('reports', '0003_suspectedcase_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspectedcase',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='geolocation.Location'),
            preserve_default=False,
        ),
    ]
