# Generated by Django 3.0.5 on 2020-04-17 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0005_auto_20200417_0713'),
        ('reports', '0005_auto_20200405_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspectedcase',
            name='location',
        ),
        migrations.AddField(
            model_name='suspectedcase',
            name='town',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='geolocation.Town'),
            preserve_default=False,
        ),
    ]
