# Generated by Django 3.0.5 on 2020-04-05 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geolocation', '0002_auto_20200405_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
