# Generated by Django 3.0.5 on 2020-04-17 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0003_region_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='region',
            old_name='address',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='receptioncenter',
            name='region',
        ),
        migrations.RemoveField(
            model_name='region',
            name='date',
        ),
        migrations.RemoveField(
            model_name='region',
            name='is_risked',
        ),
        migrations.RemoveField(
            model_name='region',
            name='is_validated',
        ),
        migrations.RemoveField(
            model_name='region',
            name='location',
        ),
        migrations.RemoveField(
            model_name='region',
            name='number_carrier',
        ),
        migrations.RemoveField(
            model_name='region',
            name='number_confirmed_cases',
        ),
        migrations.RemoveField(
            model_name='region',
            name='number_death',
        ),
        migrations.RemoveField(
            model_name='region',
            name='number_recovered',
        ),
        migrations.RemoveField(
            model_name='region',
            name='number_sick',
        ),
        migrations.RemoveField(
            model_name='region',
            name='number_suspect',
        ),
        migrations.AddField(
            model_name='region',
            name='name',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('postal_code', models.CharField(max_length=10)),
                ('number_death', models.IntegerField()),
                ('number_suspect', models.IntegerField()),
                ('number_sick', models.IntegerField()),
                ('number_confirmed_cases', models.IntegerField()),
                ('number_carrier', models.IntegerField()),
                ('number_recovered', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('is_risked', models.BooleanField(default=False)),
                ('is_validated', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocation.Location')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocation.State')),
            ],
        ),
        migrations.AddField(
            model_name='receptioncenter',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='geolocation.State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='states',
            field=models.ManyToManyField(to='geolocation.State'),
        ),
    ]
