# Generated by Django 3.0.5 on 2020-04-17 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0004_auto_20200417_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='reception_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocation.ReceptionCenter'),
        ),
    ]
