# Generated by Django 3.0.5 on 2020-04-17 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0005_auto_20200417_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptioncenter',
            name='state',
        ),
        migrations.AddField(
            model_name='receptioncenter',
            name='town',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='geolocation.Town'),
            preserve_default=False,
        ),
    ]
