# Generated by Django 3.0.5 on 2020-04-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200406_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprofile',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='is_suspect',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
