# Generated by Django 3.0.5 on 2020-06-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_embed_url', models.URLField()),
                ('video_id', models.CharField(max_length=256)),
                ('published_at', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=512)),
                ('channel_title', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('is_validated', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
